site_name: AI-Powered Job Seeker Platform
site_description: Comprehensive documentation for the AI-powered job seeker platform with dual user support, CV builder, and workflow automation
site_author: AI-legend
site_url: https://ai-legend.github.io/Job-Portal-Doc

repo_name: AI-legend/Job-Portal-Doc
repo_url: https://github.com/AI-legend/Job-Portal-Doc
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - abbr
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: 'README.md'
  - Architecture:
    - Overview: 'architecture/README.md'
    - Frontend: 'architecture/frontend.md'
    - Backend: 'architecture/backend.md'
    - Workflow: 'architecture/workflow.md'
  - API Documentation: 'api/README.md'
  - Deployment: 'deployment/README.md'
  - Development: 'development/README.md'
  - Visual Documentation:
    - Overview: 'diagrams/README.md'
    - Data Flow Diagrams: 'diagrams/data-flow-diagram.md'
    - Entity Relationship Diagrams: 'diagrams/entity-relationship-diagram.md'
    - Workflow Diagrams: 'diagrams/workflow-diagrams.md'
    - Architecture Diagrams: 'diagrams/architecture-diagrams.md'
  - Project Planning:
    - Milestones: 'PROJECT_MILESTONES.md'
    - Technology Stack: 'TECH_STACK.md'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AI-legend/Job-Portal-Doc
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/your-profile
  version:
    provider: mike

copyright: Copyright &copy; 2025 AI-legend
